export {
  CARD_SPRING,
  PRESS_TIMING_IN,
  PRESS_TIMING_OUT,
  PRESS_SCALE_BTN,
  PRESS_SCALE_FAB,
  PRESS_SCALE_ICON,
  BUTTON_TIMING_DURATION,
  MODAL_OPEN_DURATION,
  MODAL_CLOSE_DURATION,
  AUTO_SYNC_INTERVAL_MS,
  EASE_IN,
  EASE_OUT,
  EASE_OUT_CUBIC,
  EASE_IN_CUBIC,
} from './animations';

